### PR TITLE
[CELEBORN-544] Remove unnecessary PbUnregisterShuffleResponse between LifecycleManager and Master

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
UnregisterShuffleResponse is not used. remove it.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @RexXiong @waitinfuture @pan3793

**Comment by pan3793** [comment]
Seems it breaks the protocol contract.

**Comment by pan3793** [comment]
Assuming a 0.2 client communicates to 0.3 master, the client can not receive the response but got the next message returned by the server, then the channel is broken.

**Comment by AngersZhuuuu** [comment]
> Assuming a 0.2 client communicates to 0.3 master, the client can not receive the response but got the next message returned by the server, then the channel is broken.

So how about only removing client-side code in this version?

**Comment by pan3793** [comment]
> So how about only removing client-side code in this version?

I'm afraid it does not work either. The messages are pipelined in the channel, if we really decide to do this:

0.3 
- the server keeps no change
- the client changes the `ssHARetryClient.askSync[PbUnregisterShuffleResponse]` to `ssHARetryClient.send`, but keeps the decode code, consumes, and drops the response message silently.

0.4 
- remove the response message totally, both on client and server side

**Comment by pan3793** [comment]
How improvement can gain after dropping the response?

**Comment by AngersZhuuuu** [comment]
Maybe just quick return, don;t need to wait for reply.

**Comment by pan3793** [comment]
Overall, I oppose this change. The benefit looks not much comparing the impacts, unless it is proven to perform much well under certain conditions.

**Comment by AngersZhuuuu** [comment]
Ok

**Pull request closed without merging**
