### PR TITLE
[CELEBORN-673][SPARK][PERF] Improve the perf of sort-based shuffle write

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

1. `SQLShuffleWriteMetricsReporter#incWriteTime` is a performance killer, stop calling it once we insert a record
2. simplify the `incWriteTime` logic for handling large records, also including the time required for memory copying

### Why are the changes needed?

frame graph and stage duration before:

截屏2023-06-13 下午3 30 53

截屏2023-06-13 下午3 31 26

frame graph and stage duration after:

截屏2023-06-13 下午3 33 08

截屏2023-06-13 下午3 33 59

### Does this PR introduce _any_ user-facing change?

No, only perf improvement

### How was this patch tested?

tested locally.

### CODE REVIEW

**Review by AngersZhuuuu — APPROVED** [review]
Good Catch! LGTM and pls fix the wrong code

**Comment by cfmcgrady** [comment]
> Seems also we can do some refactor for `incBytesWritten`?

agreed, maybe we can do the refactor in a separate PR, as the current PR primarily focuses on optimizing performance.

**Comment by AngersZhuuuu** [comment]
> > Seems also we can do some refactor for `incBytesWritten`?
> 
> agreed, maybe we can do the refactor in a separate PR, as the current PR primarily focuses on optimizing performance.

Yea

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Will these cause the UI update lag?

**Comment by AngersZhuuuu** [comment]
> Will these cause the UI update lag?

I don't think so, UI updated after task result return to driver.

**Comment by cfmcgrady** [comment]
> > Will these cause the UI update lag?
> 
> I don't think so, UI updated after task result return to driver.

the heartbeat from executors to the driver will contain all running task metrics, and the live UI metrics will be updated once the report succeeded.

https://github.com/apache/spark/blob/70186f58a14b1f545ed5472355132f3591708e4e/core/src/main/scala/org/apache/spark/executor/Executor.scala#L1066-L1093

```scala
  /** Reports heartbeat and metrics for active tasks to the driver. */
  private def reportHeartBeat(): Unit = {
    // list of (task id, accumUpdates) to send back to the driver
    val accumUpdates = new ArrayBuffer[(Long, Seq[AccumulatorV2[_, _]])]()
    val curGCTime = computeTotalGcTime()

    if (pollOnHeartbeat) {
      metricsPoller.poll()
    }

    val executorUpdates = metricsPoller.getExecutorUpdates()

    for (taskRunner <- runningTasks.values().asScala) {
      if (taskRunner.task != null) {
        taskRunner.task.metrics.mergeShuffleReadMetrics()
        taskRunner.task.metrics.setJvmGCTime(curGCTime - taskRunner.startGCTime)
        val accumulatorsToReport =
          if (HEARTBEAT_DROP_ZEROES) {
            taskRunner.task.metrics.accumulators().filterNot(_.isZero)
          } else {
            taskRunner.task.metrics.accumulators()
          }
        accumUpdates += ((taskRunner.taskId, accumulatorsToReport))
      }
    }

    val message = Heartbeat(executorId, accumUpdates.toArray, env.blockManager.blockManagerId,
      executorUpdates)
```

**Comment by pan3793** [comment]
Anyway, the performance improvement looks nice, +1 to get it in.

**Comment by pan3793** [comment]
Thanks, merged to main/0.3

**Comment by waitinfuture** [comment]
Hi @cfmcgrady , thanks for the PR! Seems this improvement can also be applied to HashBasedShuffleWriters, could you also send a PR to improve them?

**Pull request closed without merging**
