### PR TITLE
[CELEBORN-190] doPushMergedData should also support revive multiple times, not only twice

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
I noticed that push data can revive many times but push merged data only revive twice. if some machine is not healthy in the cluster, too easy to cause job failed. We should make doPushMergedData support revive more than twice too.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @nafiyAix @waitinfuture

**Comment by waitinfuture** [comment]
LGTM, could you plz add a test case?

**Comment by waitinfuture** [comment]
needs to update style

**Comment by AngersZhuuuu** [comment]
> needs to update style

Fixed

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
