### PR TITLE
[CELEBORN-972][HELM] Enhance workingdirDiskCapacity unit parsing and fix ConfigMap is not effected for workerStatefuleSet

### PR DESCRIPTION
**Pull request by zhongqiangczq**
### What changes were proposed in this pull request?
1. fix the issue with the configmap not being mounted for worker
2. fix compatability with different workingdir's capacity byte unit types, e.g.  Gi, Ti.

### Why are the changes needed?

1. in previous pr the configmap is removed from value.yaml, but worker-statefulset.yaml still use this config, so worker pod can't mount the /opt/celeborn/conf to configmap volume.

2. in previous pr capacity is appended for workingdir, but unit type Gi is not suppored by byteStringTransformer
``` java
  java.lang.NumberFormatException: Size must be specified as bytes (b), kibibytes (k), mebibytes (m), gibibytes (g), tebibytes (t), or pebibytes(p). E.g. 50b, 100k, or 250m.Invalid suffix: "gi" 


celeborn.worker.storage.dirs=/mnt/disk1:disktype=SSD:capacity=100Gi,/mnt/disk2:disktype=SSD:capacity=100Gi,/mnt/disk3:disktype=SSD:capacity=100Gi,/mnt/disk4:disktype=SSD:capacity=100Gi
```

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?
manual on k8s
1. the issue of configMap not being mounted 
- befor this pr
```shell
kubectl get pod celeborn-worker-0 -o yaml |grep conf
  - configMap:
      name: celeborn-conf
      - configMap:
```
- after this pr
``` shell 
kubectl get pod celeborn-worker-0 -o yaml |grep conf
    - mountPath: /opt/celeborn/conf
  - configMap:
      name: celeborn-conf
      - configMap:
```
2. compatilbiy 
the NumberFormatException is not thrown after this pr.

### CODE REVIEW

**Comment by pan3793** [comment]
> fix workingdir's capacity unit error by removing char i

instead of removing "i", maybe we should support parsing all of `GiB`, `GB`, `G`

**Comment by zhongqiangczq** [comment]
> > fix workingdir's capacity unit error by removing char i
> 
> instead of removing "i", maybe we should support parsing all of `GiB`, `GB`, `G`

i agree. unit parser should be compatible with the different style.

**Comment by pan3793** [comment]
Strictly speaking `1GiB=1024MiB`, and `1GB=1000MB`, but I think we don't need to follow that, just treat `GiB` `GB` as the same thing

**Review by zwangsheng — APPROVED** [review]
LGTM for fix configmap part, thanks for catching this.

**Review by pan3793 — APPROVED** [review]

**Pull request closed without merging**
