### PR TITLE
[CELEBORN-732] Remove unused RPC ThreadDump & ThreadDumpResponse

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Remove unused RPC ThreadDump & ThreadDumpResponse

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @pan3793 @waitinfuture @FMX

**Comment by pan3793** [comment]
I guess it maybe useful if we decide to provide a Web UI on master.

**Comment by AngersZhuuuu** [comment]
> I guess it maybe useful if we decide to provide a Web UI on master.

If web UI use RPC, it reuse, but we also can get such information throw HTTP request.

**Review by pan3793 — APPROVED** [review]

**Comment by pan3793** [comment]
Merged to main/0.3

**Pull request closed without merging**
