### PR TITLE
[CELEBORN-646] Throw exception when raft client request not success.

### PR DESCRIPTION
**Pull request by RexXiong**
### What changes were proposed in this pull request?
Throw exception when raft client request not success.

### Why are the changes needed?
Ratis client may not throw exception when submit request not success. Current only LeaderNotReadyException,NotLeaderException throw out exception this may cause some inconsistent.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### CODE REVIEW

**Comment by FMX** [comment]
What will happen if a raft client failed to submit a request? Will the Master node stop?

**Comment by RexXiong** [comment]
> What will happen if a raft client failed to submit a request? Will the Master node stop?

No, currently all ratis requests are wrapped by executeWithLeaderChecker which would handle the exception.

**Review by FMX — APPROVED** [review]
LGTM.

**Comment by FMX** [comment]
There is more to do after this patch.

**Pull request closed without merging**
