### PR TITLE
[CELEBORN-192][IMPROVEMENT] Change FAILED status to REQUEST_FAILED since it's all used when RPC request failed.

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Change FAILED status to REQUEST_FAILED since it's all used when RPC request failed. Make it more accurate.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
@waitinfuture

**Comment by waitinfuture** [comment]
I think it will not cause compatible issue, but I'm not very sure. @pan3793 plz take a look

**Comment by pan3793** [comment]
I have same concern w/ @waitinfuture

**Comment by waitinfuture** [comment]
I wi

> 

I will do a manual test.

**Comment by AngersZhuuuu** [comment]
> I think it will not cause compatible issue, but I'm not very sure. @pan3793 plz take a look

It uses the same status code value, so it won't cause compatibility issue.

**Comment by waitinfuture** [comment]
> I will do a manual test.

I have done manual test:
```
1. First I deploy Celeborn using main branch.
2. Then I run a sql job normally
3. Then I replace celeborn-client-spark-3-shaded_2.12-0.2.0-SNAPSHOT.jar in spark's jar
4. Then I restart spark-sql and run job normally, things go OK
5. Then I kill a worker during shuffle write, things go OK
6. Then I upgrade one worker with this PR's code and restart
7. Then I run job, things go OK
8. Then I kill the upgraded worker during shuffle write, things go OK
```

I see log in LifecycleManager when kill a worker, which seems to cover the msg changed
```
23/01/06 16:43:10 ERROR ReducePartitionCommitHandler: AskSync CommitFiles for 10 failed (attempt 2/2).
```

**Review by waitinfuture — APPROVED** [review]
LGTM and manual test passed, merging to main.

**Pull request merged**
