### PR TITLE
[CELEBORN-1239][FOLLOWUP] Deprecate celeborn.quota.configuration.path config

### PR DESCRIPTION
**Pull request by SteNicholas**
### What changes were proposed in this pull request?

Deprecate `celeborn.quota.configuration.path` config. User `celeborn.dynamicConfig.store.fs.path` instead.

### Why are the changes needed?

`DefaultQuotaManager` is removed in #2298, which causes that `celeborn.quota.configuration.path` is useless. `celeborn.quota.configuration.path` could be deprecated that uses `celeborn.dynamicConfig.store.fs.path` to config quota.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

No.

### CODE REVIEW

**Comment by SteNicholas** [comment]
cc @AngersZhuuuu.

**Review by RexXiong — APPROVED** [review]
LGTM, thanks

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by SteNicholas** [comment]
LGTM. Mreged into main(v0.5.0).

**Pull request closed without merging**
