### PR TITLE
[CELEBORN-1037] Incorrect output for metrics of Prometheus

### PR DESCRIPTION
**Pull request by onebox-li**
### What changes were proposed in this pull request?
The new added `deadlocks` metrics in `ThreadStatesGaugeSet` is a Set<String>, which is invalid. So here add a filter at the `addGauge` extrance.

### Why are the changes needed?
Ditto

### Does this PR introduce _any_ user-facing change?
Remove the unused metrics. BTW the template use `metrics_jvm_thread_deadlock_count_Value`

### How was this patch tested?
Manual test

### CODE REVIEW

**Comment by onebox-li** [comment]
cc @FMX, please take a look if have time :)

**Comment by onebox-li** [comment]
This check failed a little strangely because those places were not changed. Can someone have a look on this or rerun the check? Thanks.

**Review by FMX — APPROVED** [review]
LGTM. Thanks. I'll merge it into main and branch 0.3.

**Comment by FMX** [comment]
Failed checks have no connection with this PR, I triggered the checks rerun.

**Comment by FMX** [comment]
After I ran CI locally, I found that this branch could not pass while the main branch could pass. There is something wrong.

**Pull request closed without merging**
