### PR TITLE
[CELEBORN-224][FOLLOWUP] Add missing license files.

### PR DESCRIPTION
**Pull request by FMX**
### What changes were proposed in this pull request?
This is a follow-up of [Celeborn-224](https://github.com/apache/incubator-celeborn/pull/1164)

### CODE REVIEW

**Comment by FMX** [comment]
Ping @WillemJiang. How about this pull request to restore the license files?

**Comment by WillemJiang** [comment]
We need to put the third-party licenses files links into the LICENSE-binary files.

**Comment by FMX** [comment]
> We need to put the third-party licenses files links into the LICENSE-binary files.

Thanks for your review. Links are added please check again.

**Comment by WillemJiang** [comment]
LGTM.

**Comment by waitinfuture** [comment]
> 

Thanks @WillemJiang for reviewing!

**Pull request merged**
