### PR TITLE
[CELEBORN-343] Add configuration for k8s cluster name

### PR DESCRIPTION
**Pull request by liugs0213**
### What changes were proposed in this pull request?
Add the k8s cluster name configuration.

### How was this patch tested?

### CODE REVIEW

**Comment by pan3793** [comment]
cc @zwangsheng

**Comment by pan3793** [comment]
@liugs0213 thanks for your contribution, please 
- open a JIRA ticket first and put it into PR name
- open PR for master, the committers will do backport if necessary
- fill the PR description as much as possible

**Comment by zwangsheng** [comment]
@liugs0213 Hello, thanks for contribution.

We don't just use  cluster name here, you need to check `master-statefuleset.yaml` & `worker-statefulset.yaml` 's command

**Review by zwangsheng — CHANGES_REQUESTED** [review]
@liugs0213 Hello, thanks for contribution.

We don't just use  cluster name here, you need to check `master-statefuleset.yaml` & `worker-statefulset.yaml` 's command

**Comment by liugs0213** [comment]
> @liugs0213 Hello, thanks for contribution.
> 
> We don't just use cluster name here, you need to check `master-statefuleset.yaml` & `worker-statefulset.yaml` 's command
hello, master and worker have added cluster configuration. It is ok to test master and worker without adding cluster configuration

**Review by zwangsheng — APPROVED** [review]
Thanks, LGTM

**Comment by waitinfuture** [comment]
@liugs0213  Thanks!  Created [JIRA](https://issues.apache.org/jira/browse/CELEBORN-343) and will cherrypick to main.

**Pull request merged**
