### PR TITLE
[DO-NOT-MERGE] Introduce new build tool `sbt`

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

Introduce new build tool `sbt`

**NOTICE AND LIMITATION :**

1. The make distribution via sbt is not supported.
2. Only the Spark 3 Shade Client is supported and has been thoroughly tested now.
3. It is advised not to use the jar packed via sbt in your production environment.

### Why are the changes needed?

The build tool `sbt` demonstrates superior speed and performance compared to `maven`.

packing the project.

```shell
> ./build/sbt
...
sbt:celeborn-parent> clean
[success] Total time: 0 s, completed 2023-6-27 11:10:29
sbt:celeborn-parent> package
...
[success] Total time: 41 s, completed 2023-6-27 11:11:12
```

packing and shading the spark 3 client

```shell

> ./build/sbt -Pspark-3.3
...
sbt:celeborn-parent> clean
[success] Total time: 1 s, completed 2023-6-27 11:13:53
sbt:celeborn-parent> project spark-3-shaded
[info] set current project to celeborn-client-spark-3-shaded (in build file:/Users/fchen/Project/bigdata/celeborn/)
sbt:celeborn-client-spark-3-shaded> assembly
...
[info] Built: /Users/fchen/Project/bigdata/celeborn/client-spark/spark-3-shaded/target/scala-2.12/celeborn-client-spark-3-shaded-assembly-0.4.0-SNAPSHOT.jar
[info] Jar hash: 323de938b2359d0b6650a60bf414bbb66cbd002d
[success] Total time: 59 s, completed 2023-6-27 11:15:05
```

only shading the spark 3 client
```
sbt:celeborn-client-spark-3-shaded> assembly
[info] Assembly jar up to date: /Users/fchen/Project/bigdata/celeborn/client-spark/spark-3-shaded/target/scala-2.12/celeborn-client-spark-3-shaded-assembly-0.4.0-SNAPSHOT.jar
[success] Total time: 3 s, completed 2023-6-27 11:17:40
```

Life becomes much easier with `sbt` :)

### Does this PR introduce _any_ user-facing change?

Yes, introduce the new build tool `sbt`

### How was this patch tested?

Manually tested

### CODE REVIEW

**Comment by cfmcgrady** [comment]
the diff between sbt and maven

```diff
diff --git a/tmp/maven-files.out b/tmp/sbt-files.out
index d56ee78..e61150c 100644
--- a/tmp/maven-files.out
+++ b/tmp/sbt-files.out
@@ -1,8 +1,6 @@
-./META-INF/DEPENDENCIES
-./META-INF/LICENSE
+./META-INF/INDEX.LIST
 ./META-INF/LICENSE.txt
 ./META-INF/MANIFEST.MF
-./META-INF/NOTICE
 ./META-INF/NOTICE.txt
 ./META-INF/io.netty.versions.properties
 ./META-INF/maven/com.google.guava/guava/pom.properties
@@ -69,16 +67,6 @@
 ./META-INF/maven/io.netty/netty-transport-udt/pom.xml
 ./META-INF/maven/io.netty/netty-transport/pom.properties
 ./META-INF/maven/io.netty/netty-transport/pom.xml
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-3-shaded_2.12/pom.properties
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-3-shaded_2.12/pom.xml
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-3_2.12/pom.properties
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-3_2.12/pom.xml
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-common_2.12/pom.properties
-./META-INF/maven/org.apache.celeborn/celeborn-client-spark-common_2.12/pom.xml
-./META-INF/maven/org.apache.celeborn/celeborn-client_2.12/pom.properties
-./META-INF/maven/org.apache.celeborn/celeborn-client_2.12/pom.xml
-./META-INF/maven/org.apache.celeborn/celeborn-common_2.12/pom.properties
-./META-INF/maven/org.apache.celeborn/celeborn-common_2.12/pom.xml
 ./META-INF/maven/org.apache.commons/commons-lang3/pom.properties
 ./META-INF/maven/org.apache.commons/commons-lang3/pom.xml
 ./META-INF/maven/org.jctools/jctools-core/pom.properties
@@ -86,7 +74,7 @@
 ./META-INF/native/liborg_apache_celeborn_shaded_netty_transport_native_epoll_aarch_64.so
 ./META-INF/native/liborg_apache_celeborn_shaded_netty_transport_native_epoll_x86_64.so
 ./META-INF/services/reactor.blockhound.integration.BlockHoundIntegration
-./celeborn-client-spark-3-shaded_2.12-0.4.0-SNAPSHOT.jar
+./celeborn-client-spark-3-shaded-assembly-0.4.0-SNAPSHOT.jar
 ./org/apache/celeborn/client/ApplicationHeartbeater$$anon$1.class
 ./org/apache/celeborn/client/ApplicationHeartbeater.class
 ./org/apache/celeborn/client/ApplyNewLocationCallContext$.class
```

**Comment by pan3793** [comment]
The SBT is extremely faster than Maven, and its interactive CLI has a better experience for running tests.

Personally, I lean to switch the building tool from Maven to SBT, as Spark does [SPARK-44173](https://issues.apache.org/jira/browse/SPARK-44173), but this needs a consensus of the community :)

**Comment by FMX** [comment]
+1. 

Glad to see this patch, maven's building is slow.

**Comment by waitinfuture** [comment]
Thanks for this PR 😄

**Review by AngersZhuuuu — COMMENTED** [review]
Could you also update this new method in doc?

**Comment by pan3793** [comment]
There is an additional benefit if we decide to migrate to SBT.

https://github.com/scalatest/scalatest-maven-plugin/issues/99

**Comment by pan3793** [comment]
Collected concerns from the PPMC:

- someone has a bad experience about sbt network, we should provide clear docs to setup the mirror to speedup the bootstrap and dependencies download
- as Celeborn supports different Spark/Flink versions, the equivalent functionality like Maven profiles should be provided via sbt too, with IDEA support.

**Comment by pan3793** [comment]
> another concern from @RexXiong is the learning curve of sbt

I definitely understand it, until I found https://spark.apache.org/developer-tools.html and try it on developing Spark

**Comment by cfmcgrady** [comment]
> someone has a bad experience about sbt network, we should provide clear docs to setup the mirror to speedup the bootstrap and dependencies download


1. for bootstrap

The bootstrap script currently supports passing environment variables `DEFAULT_ARTIFACT_REPOSITORY`  to specify an artifact repository, which enables expedited download of the launcher JAR file. 

```shell 
> rm build/sbt-launch-1.9.0.jar
> export DEFAULT_ARTIFACT_REPOSITORY=https://mirrors.huaweicloud.com/repository/maven/ && ./build/sbt
```

2. for dependencies

The Delta project provided a good [reference](https://github.com/delta-io/delta/blob/master/build/sbt-config/repositories). By default, the `sbt` will read repository URLs from the `~/.sbt/repositories` host path.


```shell

> cat ~/.sbt/repositories
[repositories]
  local
  local-preloaded-ivy: file:///${sbt.preloaded-${sbt.global.base-${user.home}/.sbt}/preloaded/}, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext]
  local-preloaded: file:///${sbt.preloaded-${sbt.global.base-${user.home}/.sbt}/preloaded/}
  huawei-central: https://mirrors.huaweicloud.com/repository/maven/
  aliyun-maven: https://maven.aliyun.com/nexus/content/groups/public
  gcs-maven-central-mirror: https://maven-central.storage-download.googleapis.com/repos/central/data/
  typesafe-ivy-releases: https://repo.typesafe.com/typesafe/ivy-releases/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
  sbt-ivy-snapshots: https://repo.scala-sbt.org/scalasbt/ivy-snapshots/, [organization]/[module]/[revision]/[type]s/[artifact](-[classifier]).[ext], bootOnly
  sbt-plugin-releases: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  bintray-spark-packages: https://dl.bintray.com/spark-packages/maven/
  typesafe-releases: https://repo.typesafe.com/typesafe/releases/
```


```
sbt:celeborn-parent> project spark-3-shaded
[info] set current project to celeborn-client-spark-3-shaded (in build file:/Users/fchen/Project/bigdata/celeborn/)
sbt:celeborn-client-spark-3-shaded> assembly
[warn] spark-core_2.12-3.3.1.jar no longer exists at /Users/fchen/Library/Caches/Coursier/v1/https/mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-core_2.12/3.3.1/spark-core_2.12-3.3.1.jar
[info] Updating
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-core_2.12/3.3.1/spark-core_2.12-3.3.1.pom
  100.0% [##########] 36.9 KiB (70.4 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-parent_2.12/3.3.1/spark-parent_2.12-3.3.1.pom
  100.0% [##########] 137.4 KiB (832.5 KiB / s)
[info] Resolved  dependencies
[info] Updating
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-sql_2.12/3.3.1/spark-sql_2.12-3.3.1.pom
  100.0% [##########] 18.0 KiB (252.9 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-launcher_2.12/3.3.1/spark-launcher_2.12-3.3.1.pom
  100.0% [##########] 8.5 KiB (128.1 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-network-shuffle_2.12/3.3.1/spark-network-shuffle_2.12-3.3.1.pom
  100.0% [##########] 8.5 KiB (87.6 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-tags_2.12/3.3.1/spark-tags_2.12-3.3.1.pom
  100.0% [##########] 5.7 KiB (34.1 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-catalyst_2.12/3.3.1/spark-catalyst_2.12-3.3.1.pom
  100.0% [##########] 11.3 KiB (59.9 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-kvstore_2.12/3.3.1/spark-kvstore_2.12-3.3.1.pom
  100.0% [##########] 8.3 KiB (44.1 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-sketch_2.12/3.3.1/spark-sketch_2.12-3.3.1.pom
  100.0% [##########] 6.2 KiB (29.8 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-unsafe_2.12/3.3.1/spark-unsafe_2.12-3.3.1.pom
  100.0% [##########] 8.1 KiB (38.5 KiB / s)
https://mirrors.huaweicloud.com/repository/maven/org/apache/spark/spark-network-common_2.12/3.3.1/spark-network-common_2.12-3.3.1.pom
  100.0% [##########] 12.4 KiB (163.1 KiB / s)
```

**Comment by pan3793** [comment]
> > as Celeborn supports different Spark/Flink versions, the equivalent functionality like Maven profiles should be provided via sbt too, with IDEA support.
> 
> Passing Maven profiles to `sbt` is currently supported. However, integration with IntelliJ IDEA has not yet been tested.

This can be achieved by

image

A further thought, we may not be limited to using Maven style, the original goal is to easily switch different properties groups, maybe we can define a `sbt-local.properties`(ignored by git), and users can override anything they want.

**Comment by pan3793** [comment]
@cfmcgrady Do you have time to start a pure SBT building system?

**Comment by pan3793** [comment]
BTW, I think we can introduce a dependency audit mechanism like [Spark](https://github.com/apache/spark/blob/master/dev/deps/spark-deps-hadoop-3-hive-2.3) does, we may need to merge `master-jars` and `worker-jars` before doing that.

**Comment by pan3793** [comment]
I think Spark's [developer-tools page](https://spark.apache.org/developer-tools.html) is a good example to follow, we can provide a similar page at https://celeborn.apache.org/community/contributor_guide/build_and_test/

**Comment by pan3793** [comment]
> I am contemplating the possibility and complexity of transitioning from a pom-based project to a pure sbt project.

Based on my experience with Spark, dual building systems always introduce inconvenience, Even after the continuous efforts of many excellent engineers, Spark's output artifacts and dependency resolve list still have some differences between sbt and maven. Thus I would argue that a pure sbt makes life easy.

**Pull request closed without merging**
