### PR TITLE
[CELEBORN-885][SPARK] Shade RoaringBitmap to avoid dependency conflicts

### PR DESCRIPTION
**Pull request by FMX**
### What changes were proposed in this pull request?
Shade roaring bitmap to void dependency conflicts.

### Why are the changes needed?
Some user reports that celeborn client will introduce roaring bitmap conflicts. 

### Does this PR introduce _any_ user-facing change?
NO.

### How was this patch tested?
GA and cluster.

### CODE REVIEW

**Comment by pan3793** [comment]
sbt should be updated too, cc @cfmcgrady

**Comment by cfmcgrady** [comment]
Would you mind updating the file `project/CelebornBuild.scala`, following the same rule as we do in the Flink assembly project?
```
          ShadeRule.rename("org.roaringbitmap.**" -> "org.apache.celeborn.shaded.org.roaringbitmap.@1").inAll
```

**Comment by pan3793** [comment]
BTW, NOTICE for the shaded module should be updated too

**Comment by FMX** [comment]
> Would you mind updating the file `project/CelebornBuild.scala`, following the same rule as we do in the Flink assembly project?
> 
> ```diff
>            val cp = (assembly / fullClasspath).value
>            cp filter { v =>
>              val name = v.data.getName
> -            !(name.startsWith("celeborn-") || name.startsWith("protobuf-java-") ||
> -              name.startsWith("guava-") || name.startsWith("netty-") || name.startsWith("commons-lang3-"))
> +            !(name.startsWith("celeborn-") ||
> +                name.startsWith("protobuf-java-") ||
> +                name.startsWith("guava-") ||
> +                name.startsWith("netty-") ||
> +                name.startsWith("commons-lang3-") ||
> +                name.startsWith("RoaringBitmap-"))
>            }
>          },
> 
>            ShadeRule.rename("com.google.protobuf.**" -> "org.apache.celeborn.shaded.com.google.protobuf.@1").inAll,
>            ShadeRule.rename("com.google.common.**" -> "org.apache.celeborn.shaded.com.google.common.@1").inAll,
>            ShadeRule.rename("io.netty.**" -> "org.apache.celeborn.shaded.io.netty.@1").inAll,
> -          ShadeRule.rename("org.apache.commons.**" -> "org.apache.celeborn.shaded.org.apache.commons.@1").inAll
> +          ShadeRule.rename("org.apache.commons.**" -> "org.apache.celeborn.shaded.org.apache.commons.@1").inAll,
> +          ShadeRule.rename("org.roaringbitmap.**" -> "org.apache.celeborn.shaded.org.roaringbitmap.@1").inAll
>          ),
> 
>          (assembly / assemblyMergeStrategy) := {
> ```

OK，I‘ll update it.

> BTW, NOTICE for the shaded module should be updated too

RoaringBitmap has no notice and its using Apache Licencese V2. We already contains its license info in LICENSE-binary file.

> Would you mind updating the file `project/CelebornBuild.scala`, following the same rule as we do in the Flink assembly project?
> 
> ```diff
>            val cp = (assembly / fullClasspath).value
>            cp filter { v =>
>              val name = v.data.getName
> -            !(name.startsWith("celeborn-") || name.startsWith("protobuf-java-") ||
> -              name.startsWith("guava-") || name.startsWith("netty-") || name.startsWith("commons-lang3-"))
> +            !(name.startsWith("celeborn-") ||
> +                name.startsWith("protobuf-java-") ||
> +                name.startsWith("guava-") ||
> +                name.startsWith("netty-") ||
> +                name.startsWith("commons-lang3-") ||
> +                name.startsWith("RoaringBitmap-"))
>            }
>          },
> 
>            ShadeRule.rename("com.google.protobuf.**" -> "org.apache.celeborn.shaded.com.google.protobuf.@1").inAll,
>            ShadeRule.rename("com.google.common.**" -> "org.apache.celeborn.shaded.com.google.common.@1").inAll,
>            ShadeRule.rename("io.netty.**" -> "org.apache.celeborn.shaded.io.netty.@1").inAll,
> -          ShadeRule.rename("org.apache.commons.**" -> "org.apache.celeborn.shaded.org.apache.commons.@1").inAll
> +          ShadeRule.rename("org.apache.commons.**" -> "org.apache.celeborn.shaded.org.apache.commons.@1").inAll,
> +          ShadeRule.rename("org.roaringbitmap.**" -> "org.apache.celeborn.shaded.org.roaringbitmap.@1").inAll
>          ),
> 
>          (assembly / assemblyMergeStrategy) := {
> ```

I'll update it.

**Comment by FMX** [comment]
> BTW, NOTICE for the shaded module should be updated too

RoarbingBitmap has no notice and its using apache license. We already contains its license info in LICENSE-binary. Is there anything else need to put in NOTICE?

**Comment by pan3793** [comment]
Not the NOTICE-binary, technically, each jar we published to maven central should contain its own NOTICE file, which reflects the real content itself. For shaded jars, we need to maintain the NOTICE file manually.

**Comment by FMX** [comment]
> Not the NOTICE-binary, technically, each jar we published to maven central should contain its own NOTICE file, which reflects the real content itself. For shaded jars, we need to maintain the NOTICE file manually.

Any reference for bundle notice into jar file？

**Comment by pan3793** [comment]
https://github.com/apache/kyuubi/tree/master/externals/kyuubi-spark-sql-engine/src/main/resources/META-INF

**Review by pan3793 — APPROVED** [review]

**Pull request closed without merging**
