### PR TITLE
[CELEBORN-1294] Fix spark.shuffle.compress not work

### PR DESCRIPTION
**Pull request by JinHelin404**
### What changes were proposed in this pull request?

make spark conf spark.shuffle.compress works for celeborn

### Why are the changes needed?

celeborn should be compatible with spark conf spark.shuffle.compress

### Does this PR introduce _any_ user-facing change?
no

### CODE REVIEW

**Comment by JinHelin404** [comment]
> > celeborn should be compatible with spark conf spark.shuffle.compress
> 
> should we?
> 
> the options are not same actually, Celeborn only supports LZ4 and ZSTD

Hi pan, thanks for reviewing! 

The compression format of celeborn may be inconsistent with spark. But does celeborn client need to be compatible with common configurations like spark.shuffle.compress?

For example, my sparkapp is configured with spark.shuffle.compress=false but celeborn still compresses the shuffle data, which is beyond my expectation.

**Comment by JinHelin404** [comment]
> > > celeborn should be compatible with spark conf spark.shuffle.compress
> > 
> > 
> > should we?
> > the options are not same actually, Celeborn only supports LZ4 and ZSTD
> 
> @pan3793 Hi pan, thanks for reviewing!
> 
> The compression format of celeborn may be inconsistent with spark. But does celeborn client need to be compatible with common configurations like spark.shuffle.compress?
> 
> For example, my sparkapp is configured with spark.shuffle.compress=false but celeborn still compresses the shuffle data, which is beyond my expectation.

@pan3793  Or may we need some logs to show that spark.shuffle.xxx is not effective when using celeborn?

**Comment by FMX** [comment]
> > > celeborn should be compatible with spark conf spark.shuffle.compress
> > 
> > 
> > should we?
> > the options are not same actually, Celeborn only supports LZ4 and ZSTD
> 
> @pan3793 Hi pan, thanks for reviewing!
> 
> The compression format of celeborn may be inconsistent with spark. But does celeborn client need to be compatible with common configurations like spark.shuffle.compress?
> 
> For example, my sparkapp is configured with spark.shuffle.compress=false but celeborn still compresses the shuffle data, which is beyond my expectation.

Why will you need uncompressed shuffle data in Celeborn? Celeborn will compress shuffle data by default because there is a performance benefit.

**Comment by pan3793** [comment]
> But does celeborn client need to be compatible with common configurations like spark.shuffle.compress?
>
> For example, my sparkapp is configured with spark.shuffle.compress=false but celeborn still compresses the shuffle data, which is beyond my expectation.

I don't think we should, we expect that users search the [Celeborn configuration page](https://celeborn.apache.org/docs/latest/configuration/) with the keywords `compression` if they want to tune the compression algorithm and levels.

additionally, conditional mapping spark internal configuration may involve a lot of inconsistency. for example, should we map `spark.shuffle.service.port` to celeborn's something? due the different implementation details, Celeborn won't benefit from zstd buffer pool feature, if we map `spark.shuffle.compress` to `celeborn.shuffle.compression.codec`, how could the user know that `spark.io.compression.zstd.bufferPool.enabled` does not take effect?

**Comment by JinHelin404** [comment]
> Why will you need uncompressed shuffle data in Celeborn? Celeborn will compress shuffle data by default because there is a performance benefit.

@FMX I'm testing how much celeborn can benefit from shuffle compress, and whether there will be any performance regression due to data copying

**Comment by JinHelin404** [comment]
> additionally, conditional mapping spark internal configuration may involve a lot of inconsistency. for example, should we map `spark.shuffle.service.port` to celeborn's something? due the different implementation details, Celeborn won't benefit from zstd buffer pool feature, if we map `spark.io.compression.codec` to `celeborn.shuffle.compression.codec`, how could the user know that `spark.io.compression.zstd.bufferPool.enabled` does not take effect?

Make sense! So should we add some logs to show that spark.shuffle.xxx will not take effect when using celeborn?

**Comment by pan3793** [comment]
> should we add some logs to show that spark.shuffle.xxx will not take effect when using celeborn?

I'm neutral on this. For me it's obvious. If you want to add such logs, `spark.shuffle.xxx` is not sufficient

**Comment by waitinfuture** [comment]
> > additionally, conditional mapping spark internal configuration may involve a lot of inconsistency. for example, should we map `spark.shuffle.service.port` to celeborn's something? due the different implementation details, Celeborn won't benefit from zstd buffer pool feature, if we map `spark.io.compression.codec` to `celeborn.shuffle.compression.codec`, how could the user know that `spark.io.compression.zstd.bufferPool.enabled` does not take effect?
> 
> Make sense! So should we add some logs to show that spark.shuffle.xxx will not take effect when using celeborn?

Thanks @JinHelin404 for looking into this. Another reason why Celeborn doesn't automatically map Spark's configuration is that Celeborn supports multiple engines (i.e. Spark, Flink, MR, MR3), it unreasonable to respect a particular engine's configuration :)

**Pull request closed without merging**
