### PR TITLE
[CELEBORN-745] Match TransportMessage type use number instead of enum

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Match TransportMessage type use number not enum to support change MessageType name，after this pr, then we can change the MessageType name.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @pan3793 @waitinfuture @FMX @RexXiong

**Comment by pan3793** [comment]
I think this is a good approach, we should change it before 0.3, then we can change the enum name after 0.3 (maybe 0.3.1 because it's internal change)

**Comment by RexXiong** [comment]
Field addition and deletion are both compatible when deserialization with same serialVersionUID of java object, so I add a new field messageTypeValue for TransportMessage and mark messageType as deprecated, then messageType can be removed in next version. This change can compatible with old clients -> new server. @pan3793  @AngersZhuuuu

**Comment by AngersZhuuuu** [comment]
cc @waitinfuture @FMX

**Review by pan3793 — APPROVED** [review]

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main/0.3

**Pull request closed without merging**
