### PR TITLE
[CELEBORN-1111] Supporting connection to HDFS with Kerberos authentication enabled

### PR DESCRIPTION
**Pull request by liujiayi771**
### What changes were proposed in this pull request?
Adding Kerberos support for HDFS storage type.

The following five parameters need to be configured:
| key | value |
| :--: | :--: |
| celeborn.storage.hdfs.kerberos.enabled | true |
| celeborn.storage.hdfs.kerberos.principal | user@REALM |
| celeborn.storage.hdfs.kerberos.keytab | /path/test.keytab |
| celeborn.hadoop.hadoop.security.authorization | kerberos |
| celeborn.hadoop.dfs.namenode.kerberos.principal | hdfs/_HOST@REALM |

### Why are the changes needed?
Connecting to HDFS with Kerberos enabled requires support for keytab login.

### Does this PR introduce _any_ user-facing change?
Add 3 configurations.
celeborn.storage.hdfs.kerberos.enabled
celeborn.storage.hdfs.kerberos.principal
celeborn.storage.hdfs.kerberos.keytab

### How was this patch tested?
Test in Kerberos enabled HDFS cluster.

### CODE REVIEW

**Comment by waitinfuture** [comment]
Thanks @liujiayi771 for this PR! Please run `UPDATE=1 build/mvn clean test -pl common -am -Dtest=none -DwildcardSuites=org.apache.celeborn.ConfigurationSuite` to automatically generate config docs, and `dev/reformat` to format style. See https://github.com/apache/incubator-celeborn/blob/main/CONTRIBUTING.md#code-style

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main(v0.4.0)/branch-0.3(v0.3.2). BTW, could you add a section in document showing an example of using this?

**Comment by waitinfuture** [comment]
Hi @FMX , could you paste a detailed example of connecting to kerberized HDFS?

**Comment by FMX** [comment]
OK, I'll added a document about how to use this PR.

**Pull request closed without merging**
