### PR TITLE
[CELEBORN-1065] Prevent the local variable 'time' declared in one 'switch' branch and used in another

### PR DESCRIPTION
**Pull request by bowenliang123**
### What changes were proposed in this pull request?
- Minor code improvement in `MetaHandler`
  - Local variable 'time' declared in one 'switch' branch `AppHeartbeat` and used in another branch `WorkerHeartbeat`

### Why are the changes needed?

- Incorrect code pattern.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI tests.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
Pls create a jira ticket  for this and change the pr title

**Comment by bowenliang123** [comment]
Sure.

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main(v0.4.0).

**Comment by bowenliang123** [comment]
Thanks for the review and merging. 
It's my first contribution to Apache Celeborn. 
I'm looking forward to participating in more feature development and improvements.

**Pull request closed without merging**
