### PR TITLE
[CELEBORN-1061] Fix the bug if `celeborn.client.spark.shuffle.writer` is sort and `celeborn.client.spark.push.sort.pipeline.enabled` is false

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
`SparkShuffleManager` may throws `NullPointerException` if `celeborn.client.spark.shuffle.writer` is sort and `celeborn.client.spark.push.sort.pipeline.enabled` is false.

### Why are the changes needed?
Currently, if `celeborn.client.spark.shuffle.writer` is sort and `celeborn.client.spark.push.sort.pipeline.enabled` is false, the `SparkShuffleManager.asyncPushers` will be null. When calling `SparkShuffleManager. getWriter `, the null pusher thread used to construct `SortBasedShuffleWriter`. `SortBasedPusher.triggerPush` causes `NullPointerException`.

### Does this PR introduce _any_ user-facing change?
Yes.
Fix a bug.

### How was this patch tested?
Exists test cases.

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
spark-2 module need to change too?

**Comment by pan3793** [comment]
There was an unrecoverable design issue identified when `celeborn.client.spark.push.sort.pipeline.enabled` is true, actually, the community decided to delete this feature in the next release.

**Comment by beliefer** [comment]
> There was an unresolvable design issue identified when `celeborn.client.spark.push.sort.pipeline.enabled` is true, actually, the community decided to delete this feature in the next release.

Do we need to solve this problem first?

**Comment by pan3793** [comment]
@beliefer I think we can minimize the change and port this patch to branch-0.3 too. then delete the related code on the main branch

**Comment by beliefer** [comment]
@AngersZhuuuu @pan3793 It's my fatal. 
SortBasedShuffleWriter checked `celeborn.client.spark.push.sort.pipeline.enabled` again, please see:
https://github.com/apache/incubator-celeborn/blob/2758df713ead7fd78fdee9f8a2af2ad2ce377fa9/client-spark/spark-2/src/main/java/org/apache/spark/shuffle/celeborn/SortBasedShuffleWriter.java#L130

**Pull request closed without merging**
