### PR TITLE
[CELEBORN-150][BUILD] Reduce binary tarball size by sharing jars

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

This PR proposes to reduce binary tarball size by sharing jars, the idea is to put all jars into `jars/` and create soft links in `master-jars/` and `worker-jars`.

### Why are the changes needed?

Close https://github.com/apache/incubator-celeborn/issues/765

There are lots of duplicated jars under `master-jars/` and `worker-jars/`, the sharing of jars dramatically reduced the binary tarball size.

```
➜  apache-celeborn git:(main) ll apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
-rw-r--r-- 1 chengpan chengpan 144M Dec 16 03:59 apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
```

```
➜  apache-celeborn git:(CELEBORN-150) ll apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
-rw-r--r-- 1 chengpan chengpan 86M Dec 16 03:47 apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually test.

### CODE REVIEW

**Comment by pan3793** [comment]
cc @SzyWilliam @waitinfuture @zwangsheng

**Comment by pan3793** [comment]
@SzyWilliam have a quick look on the jar size, ratis jars are quite large, by sharing jars in this way, adding the ratis shell will not increase the binary tarball size much.

**Comment by FMX** [comment]
@pan3793 I can't reproduce your result. Commit is e91797a.

> (base) ➜  celeborn git:(CELEBORN-150) ll apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
> -rw-r--r--@ 1 minxfeng  staff   219M 12 16 10:46 apache-celeborn-0.2.0-SNAPSHOT-bin.tgz
> (base) ➜  celeborn git:(CELEBORN-150) du -sh apache-celeborn-0.2.0-SNAPSHOT-bin
> 244M	apache-celeborn-0.2.0-SNAPSHOT-bin
> (base) ➜  celeborn git:(CELEBORN-150)

**Comment by pan3793** [comment]
@FMX please try again, it cause by difference behavior of `cp -r` on linux and macOS, fixed it by using `cp -R`.

**Review by FMX — APPROVED** [review]
LGTM. This pr was tested on the cluster, it works well.

**Pull request merged**
