### PR TITLE
[CELEBORN-230] AppDiskUsageSnapShot overrides equals() without override hashCode()

### PR DESCRIPTION
**Pull request by kaijchen**

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
pls run `./dev/reformat` to format the code

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Comment by kaijchen** [comment]
Thanks @AngersZhuuuu and @waitinfuture for the review.

**Pull request merged**
