### PR TITLE
[CELEBORN-739] Rename HeartbeatResponse to HeartbeatFromWorkerResponse

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Rename HeartbeatResponse to HeartbeatFromWorkerResponse

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @waitinfuture @pan3793 @FMX

**Comment by waitinfuture** [comment]
I'm afraid change message name will cause compatibility issue. cc @pan3793

**Comment by pan3793** [comment]
> I'm afraid change message name will cause compatibility issue. cc @pan3793

I think no, the protobuf binary encoding format does not contains the message name

**Comment by AngersZhuuuu** [comment]
> I think no, the protobuf binary encoding format does not contains the message name

+1

**Review by pan3793 — APPROVED** [review]

**Review by FMX — APPROVED** [review]
LGTM. I think it's OK.

**Comment by pan3793** [comment]
Thanks, merged to main/0.3

**Pull request closed without merging**
