### PR TITLE
[CELEBORN-846] Remove unused updateReleaseSlotsMeta in master side

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
As title

### Why are the changes needed?

CELEBORN-791 removed sending the ReleaseSlotsRequest from worker, so Master is not required to handle it.

### CODE REVIEW

**Comment by pan3793** [comment]
I suppose the change is safe, and the protobuf definition can be cleaned too.

@FMX could you please take a look? as you touched this part last time.

**Comment by AngersZhuuuu** [comment]
> I suppose the change is safe, and the protobuf definition can be cleaned too.
> 
> @FMX could you please take a look? as you touched this part last time.

Yea, cleaned

**Comment by FMX** [comment]
OK, I'll check this PR.

**Review by FMX — APPROVED** [review]
LGTM. I think this change is safe while older clients will get some exceptions.

**Comment by pan3793** [comment]
This cause problem on using 0.3.0 client access to 0.3.1-SNAPSHOT server

**Pull request closed without merging**
