### PR TITLE
[CELEBORN-1113] Bump Hadoop client version from 3.2.4 to 3.3.6

### PR DESCRIPTION
**Pull request by cxzl25**
### Why are the changes needed?

[[HADOOP-17098](https://issues.apache.org/jira/browse/HADOOP-17098)] Reduce Guava dependency in Hadoop source code

The higher version of hadoop client removes many guava-related methods, which avoids some conflicts on guava.

`hadoop-client-api` 3.3.6
`hadoop-client-runtime` 3.3.6

### CODE REVIEW

**Comment by FMX** [comment]
Bump Hadoop client version from 3.2.4 to 3.3.6 will make Celeborn can not access HDFS 2.x cluster. I think it's ok to bump hadoop version but you'll need to test the cluster compatibility.

**Comment by cxzl25** [comment]
> Bump Hadoop client version from 3.2.4 to 3.3.6 will make Celeborn can not access HDFS 2.x cluster. I think it's ok to bump hadoop version but you'll need to test the cluster compatibility.

Test file operations such as mkdir, ls, put, get, etc.


| Hadoop Server | Hadoop client 2.x | Hadoop client 3.2.4 | Hadoop client 3.3.6 |
| ------------- | ----------------- | ------------------- | ------------------- |
| 2.2.0         | YES               | Write failed        | Write failed        |
| 2.3.0         | YES               | YES                 | YES                 |
| 2.6.0         | YES               | YES                 | YES                 |
| 2.10.0        | YES               | YES                 | YES                 |



### Write failed
```java
2023-11-15 17:41:58,502 WARN hdfs.DataStreamer: DataStreamer Exception
java.lang.NullPointerException
	at org.apache.hadoop.hdfs.DataStreamer.createBlockOutputStream(DataStreamer.java:1805)
	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1728)
	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:713)
put: java.lang.NullPointerException
```

`nodeStorageIDs`==null  NPE
org.apache.hadoop.hdfs.DataStreamer#createBlockOutputStream
```java
        new Sender(out).writeBlock(blockCopy, nodeStorageTypes[0], accessToken,
            dfsClient.clientName, nodes, nodeStorageTypes, null, bcs,
            nodes.length, block.getNumBytes(), bytesSent, newGS,
            checksum4WriteBlock, cachingStrategy.get(), isLazyPersistFile,
            (targetPinnings != null && targetPinnings[0]), targetPinnings,
            nodeStorageIDs[0], nodeStorageIDs);
```


Storage ID was introduced in 2.3.0, causing an error when writing to HDFS 2.2.0 if it is greater than or equal to 3.0 (HDFS-9807).



HDFS-2832: Enable support for heterogeneous storages in HDFS
https://issues.apache.org/jira/browse/HDFS-2832
Fix Version/s: 2.3.0

HDFS-9807. Add an optional StorageID to writes.
https://issues.apache.org/jira/browse/HDFS-9807
Fix Version/s:3.0.0-alpha4

**Review by FMX — APPROVED** [review]
LGTM. Thanks. Merged into main.

**Comment by cfmcgrady** [comment]
the main branch CI failed after applying this change. cc @FMX @cxzl25 

https://github.com/apache/incubator-celeborn/actions/runs/7057185645/job/19210402302

```
[info] org.apache.celeborn.tests.mr.WordCountTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: org/bouncycastle/operator/OperatorCreationException
[info]   at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager$RMActiveServices.serviceInit(ResourceManager.java:888)
[info]   at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
[info]   at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.createAndInitActiveServices(ResourceManager.java:1410)
[info]   at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:344)
[info]   at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
[info]   at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:359)
[info]   at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:129)
[info]   at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:494)
[info]   at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
[info]   at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:109)
[info]   at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:327)
[info]   at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
[info]   at org.apache.celeborn.tests.mr.WordCountTest.beforeAll(WordCountTest.scala:78)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at org.apache.celeborn.tests.mr.WordCountTest.run(WordCountTest.scala:45)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[114](https://github.com/apache/incubator-celeborn/actions/runs/7057185645/job/19210402302#step:4:115)9)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:750)
```

**Pull request closed without merging**
