### PR TITLE
[CELEBORN-1166] Avoid calling parmap when setup endpoint

### PR DESCRIPTION
**Pull request by waitinfuture**
### What changes were proposed in this pull request?
As title

### Why are the changes needed?
One user reported that LifecycleManager's parmap can create huge number of threads and causes OOM.

image

There are four places where parmap is called:

1. When LifecycleManager commits files
2. When LifecycleManager reserves slots
3. When LifecycleManager setup connection to workers
4. When StorageManager calls close

This PR fixes the third one. To be more detail, this PR eliminates `parmap` when setup connection to workers, and also replaces `askSync` with `ask`.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Manual test and GA.

### CODE REVIEW

**Comment by waitinfuture** [comment]
cc @pan3793 @cfmcgrady

**Review by pan3793 — APPROVED** [review]

**Comment by waitinfuture** [comment]
I setup a 594-worker cluster(on 6 nodes, 99 workers per node) and timed this PR and previously parmap block 4 times, using benchmark spark.sparkContext.parallelize(1 to 8000, 8000).flatMap( _ => (1 to 5000000).iterator.map(num => num)).repartition(8000).count, the results are:

this PR: 339ms/60ms/58ms/57ms
parmap: 1335ms/621ms/253ms/591ms

So this PR uses much less threads while has better performance.

**Comment by waitinfuture** [comment]
Thanks, merging to main(v0.4.0)/branch-0.3(v0.3.2)

**Comment by cfmcgrady** [comment]
late LGTM

**Pull request closed without merging**
