### PR TITLE
[CELEBORN-806] Correct the conf key `celeborn.data.io.threads` within the class `ShuffleClientImpl`

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

As title

### Why are the changes needed?

The configuration key `celeborn.data.io.threads` underwent an inadvertent modification in https://github.com/apache/incubator-celeborn/pull/1077

### Does this PR introduce _any_ user-facing change?

Bug fix

### How was this patch tested?

Pass GA

### CODE REVIEW

**Comment by cfmcgrady** [comment]
Furthermore, I have been unable to locate any documentation pertaining to the `data` module.

**Review by pan3793 — APPROVED** [review]
Jesus ...

**Comment by cfmcgrady** [comment]
> Furthermore, I have been unable to locate any documentation pertaining to the `data` module.

Is the lack of documentation for the `data` module due to oversight or has the module's configurations been deprecated? cc @pan3793 @waitinfuture

**Comment by pan3793** [comment]
The current auto-generated configuration docs indeed lack the description of modules, I'm not sure if @waitinfuture and @AngersZhuuuu have any idea to improve it.

**Comment by waitinfuture** [comment]
> > Furthermore, I have been unable to locate any documentation pertaining to the `data` module.
> 
> Is the lack of documentation for the `data` module due to oversight or has the module's configurations been deprecated? cc @pan3793 @waitinfuture

- `DATA_MODULE` is for ShuffleClient, used for both `push` and `fetch`
- `PUSH_MODULE` is for Worker, used for push server and push-related logic in Worker: 1. trim; 2. push timeout
- `REPLICATE_MODULE` is for Worker, used for replicate server and replicate-related logic in Worker: trim
- `FETCH_MODULE` is for Worker, used for fetch server
- `RPC_MODULE` is used for Master/Worker/ShuffleClient/LifecycleManager, used for RPC

I do think it's necessary to explain in the documentation. cc @cfmcgrady @pan3793 @AngersZhuuuu

**Pull request closed without merging**
