### PR TITLE
[CELEBORN-1019] Avoid magic strings copy from Spark SQLConf

### PR DESCRIPTION
**Pull request by beliefer**
### What changes were proposed in this pull request?
Avoid magic strings copy from Spark `SQLConf`.

### Why are the changes needed?
Currently, the spark integration uses many magic strings copy from Spark `SQLConf`.
Since we have already depend on Spark, references the variable from Spark is better.

### Does this PR introduce _any_ user-facing change?
No.
Just update the inner implementation.

### How was this patch tested?
Exists test cases.

### CODE REVIEW

**Comment by cfmcgrady** [comment]
please run `./dev/reformat` to automatically reformat code style.

**Comment by waitinfuture** [comment]
Hi @beliefer , I've reformatted the style, but there is  another problem. Since some of the spark configs are introduced in higher spark version, seems we should not change `SparkShuffleManagerSuite`, ``SparkShuffleManagerSuite`, `SkewJoinSuite` and `SparkTestBase`.

**Comment by beliefer** [comment]
> Hi @beliefer , I've reformatted the style, but there is another problem. Since some of the spark configs are introduced in higher spark version, seems we should not change `CelebornShuffleManagerSuite` in spark-2 directory, `SkewJoinSuite` and `SparkTestBase`.

Thank you. I will check them.

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main/0.3

**Comment by beliefer** [comment]
@waitinfuture @cfmcgrady Thank you!

**Pull request closed without merging**
