### PR TITLE
[CELEBORN-1218] Optimize dataPusher to get partitionLocationMap only once

### PR DESCRIPTION
**Pull request by lyy-pineapple**
### What changes were proposed in this pull request?
dataPusher fetches partitionLocationMap only once outside the loop.

### Why are the changes needed?
If an exception occurs while obtaining partitionLocationMap in dataPusher.takePushTasks, it will result in attempting to fetch partitionLocationMap for each iteration in the workingQueue traversal. This leads to an unusually prolonged job execution time.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Through existing uts

### CODE REVIEW

**Review by FMX — APPROVED** [review]
LGTM.

**Comment by FMX** [comment]
@RexXiong  How about your opinion?

**Review by mridulm — APPROVED** [review]
Looks good to me.

**Comment by pan3793** [comment]
Thanks, merged to main/0.4.0

**Pull request closed without merging**
