### PR TITLE
[CELEBORN-1255][FOLLOWUP] Fix MR UT

### PR DESCRIPTION
**Pull request by FMX**
### What changes were proposed in this pull request?
1. Fix dependencies failure.
2. Upload yarn cluster directory if MR UT fails.

### Why are the changes needed?
To fix MR UT failures.

### Does this PR introduce _any_ user-facing change?
NO.

### How was this patch tested?
GA.

### CODE REVIEW

**Review by RexXiong — APPROVED** [review]
LGTM, thanks!

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main(v0.5.0)

**Comment by cfmcgrady** [comment]
> LGTM, thanks! Merging to main(v0.5.0)

the `branch-0.4` CI is also broken. @waitinfuture 

https://github.com/apache/incubator-celeborn/actions/runs/7948486741/job/21698560139

**Comment by waitinfuture** [comment]
> > LGTM, thanks! Merging to main(v0.5.0)
> 
> the `branch-0.4` CI is also broken. @waitinfuture
> 
> https://github.com/apache/incubator-celeborn/actions/runs/7948486741/job/21698560139

Cherrypicked https://github.com/apache/incubator-celeborn/commit/ac8b3035008dc775735185630aa01198bd4399bc

**Pull request closed without merging**
