### PR TITLE
[CELEBORN-81] Add codecov.

### PR DESCRIPTION
**Pull request by FMX**
# [CELEBORN-81]Add codecov.

### How was this patch tested?

/cc @related-reviewer

/assign @main-reviewer

### CODE REVIEW

**Comment by FMX** [comment]
Waiting for the Jira ticket 
https://issues.apache.org/jira/browse/INFRA-23972?orderby=cf%5B12313920%5D+ASC%2C+priority+DESC%2C+updated+DESC

**Comment by FMX** [comment]
It works without token but unstable. So I think this pr can be merged.

**Comment by FMX** [comment]
According the INFRA ticket comments, I think the codecov is configured and usable.

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Comment by pan3793** [comment]
The JIRA is not closed correctly.

**Comment by FMX** [comment]
That is true and we don’t know why the Jira ticket won’t be closed after the pull request is merged.
在 2022年12月13日 +0800 17:13，Cheng Pan ***@***.***>，写道：

**Pull request merged**
