### PR TITLE
[CELEBORN-822][FOLLOWUP] Format the example code in the docs/README.md

### PR DESCRIPTION
**Pull request by cfmcgrady**
### What changes were proposed in this pull request?

As title

### Why are the changes needed?

make it more clarity and readability

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass CI

### CODE REVIEW

**Comment by cfmcgrady** [comment]
@pan3793 @waitinfuture

**Comment by pan3793** [comment]
Can we strip the leading timestamp from logs too?

**Comment by cfmcgrady** [comment]
> Can we strip the leading timestamp from logs too?

done

**Review by pan3793 — APPROVED** [review]

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks! Merging to main.

**Pull request closed without merging**
