### PR TITLE
[CELEBORN-584] Worker side should expose push/replicate/fetch Netty allocator metrics

### PR DESCRIPTION
**Pull request by AngersZhuuuu**
### What changes were proposed in this pull request?
Worker side should expose Netty allocator metrics

### CODE REVIEW

**Comment by AngersZhuuuu** [comment]
ping @FMX @waitinfuture

**Comment by FMX** [comment]
How about updating monitoring docs?

**Comment by AngersZhuuuu** [comment]
> How about updating monitoring docs?

Yea

**Comment by AngersZhuuuu** [comment]
> How about updating monitoring docs?

Updated

**Review by FMX — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
