### PR TITLE
Revert "[CELEBORN-255] Add counter of outstandingFetches, outstanding…

### PR DESCRIPTION
**Pull request by cfmcgrady**
…Rpcs and outstandingPushes to metrics"

This reverts commit bfa341c32f362b64dd69b84fc54934cf8224200c.

### Why are the changes needed?

https://github.com/apache/incubator-celeborn/pull/1992#issuecomment-1776760369

### CODE REVIEW

**Review by pan3793 — APPROVED** [review]

**Comment by cfmcgrady** [comment]
thanks, merging to main(v0.4.0).

**Comment by SteNicholas** [comment]
@cfmcgrady, I will fix the bug of adding counter of outstandingFetches, outstandingRpcs and outstandingPushes to metrics .

**Comment by waitinfuture** [comment]
> thanks, merging to main(v0.4.0).

Hi @cfmcgrady , seems branch-0.3 also needs to revert

**Comment by cfmcgrady** [comment]
> > thanks, merging to main(v0.4.0).
> 
> Hi @cfmcgrady , seems branch-0.3 also needs to revert

raised a new PR https://github.com/apache/incubator-celeborn/pull/2039 for branch-0.3

**Pull request closed without merging**
