### PR TITLE
[CELEBORN-774] Pullout celeborn.rpc.dispatcher.threads to CelebornConf

### PR DESCRIPTION
**Pull request by pan3793**
### What changes were proposed in this pull request?

Pullout hardcoded `celeborn.rpc.dispatcher.numThreads` to `CelebornConf` and rename it to `celeborn.rpc.dispatcher.threads` to align with existing configuration style

### Why are the changes needed?

Pullout inline configuration to `CelebornConf`, and expose it in configuration docs

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass GA.

### CODE REVIEW

**Comment by pan3793** [comment]
BTW, I notice the current `Dispatcher` code is port for Spark 2.x, SPARK-29398 changed it a lot in Spark 3.0, we may want to update the code in the future if necessary.

**Review by cfmcgrady — APPROVED** [review]
LGTM

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Comment by pan3793** [comment]
Thanks, merged to main/0.3

**Pull request closed without merging**
