### PR TITLE
[CELEBORN-495] Leader should step down when its metadata directory has IO exception

### PR DESCRIPTION
**Pull request by xunxunmimi5577**
### What changes were proposed in this pull request?
Add a notifyLogFailed method implementation in class StateMachine and a stepDown method in class HARaftServer and relative UT.

### Why are the changes needed?
https://issues.apache.org/jira/projects/CELEBORN/issues/CELEBORN-495?filter=allopenissues

If the metadata directory of leader has some exceptions(Input/Output error in my case) , resulting in IOException of log entries, the leader may not be able to process the requests anymore, but it will not step down, as a result, the service will be unavailable. 

LifecycleManager's log:
```
ERROR RssHARetryClient: Send rpc with failure, has tried 0, max try 15!
com.aliyun.emr.rss.common.rpc.RpcTimeoutException: Futures timed out after [30 seconds]. This timeout is controlled by rss.haclient.rpc.askTimeout
  at com.aliyun.emr.rss.common.rpc.RpcTimeout.com$aliyun$emr$rss$common$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:46)
  at com.aliyun.emr.rss.common.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:61)
  at com.aliyun.emr.rss.common.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:57)
  at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
  at com.aliyun.emr.rss.common.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
  at com.aliyun.emr.rss.common.haclient.RssHARetryClient.sendMessageInner(RssHARetryClient.java:148)
  at com.aliyun.emr.rss.common.haclient.RssHARetryClient.lambda$send$0(RssHARetryClient.java:111)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
  at com.aliyun.emr.rss.common.util.ThreadUtils$.awaitResult(ThreadUtils.scala:220)
  at com.aliyun.emr.rss.common.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:74)
  ... 7 more
```

Master's logs:
```
[ERROR] - org.apache.ratis.server.leader.LogAppenderDaemon.run(LogAppenderDaemon.java:86) - node1@group-5869630CF75A->node2-LogAppenderDefault-LogAppenderDaemon failed
org.apache.ratis.server.raftlog.RaftLogIOException: Log already failed at index 255 for task WriteLog:255: (t:1, i:255), STATEMACHINELOGENTRY, StateMachineLogEntryProto:42@client-DC0FB96009FC
        at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogWorker.run(SegmentedRaftLogWorker.java:313) ~[master-0.1.0-shaded.jar:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_342]
Caused by: java.io.IOException: Input/output error
        at sun.nio.ch.FileDispatcherImpl.seek0(Native Method) ~[?:1.8.0_342]
        at sun.nio.ch.FileDispatcherImpl.seek(FileDispatcherImpl.java:76) ~[?:1.8.0_342]
        at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:264) ~[?:1.8.0_342]
        at org.apache.ratis.server.raftlog.segmented.BufferedWriteChannel.preallocateIfNecessary(BufferedWriteChannel.java:72) ~[master-0.1.0-shaded.jar:?]
        at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogOutputStream.preallocateIfNecessary(SegmentedRaftLogOutputStream.java:139) ~[master-0.1.0-shaded.jar:?]
        at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogOutputStream.write(SegmentedRaftLogOutputStream.java:90) ~[master-0.1.0-shaded.jar:?]
        at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogWorker$WriteLog.execute(SegmentedRaftLogWorker.java:510) ~[master-0.1.0-shaded.jar:?]
        at org.apache.ratis.server.raftlog.segmented.SegmentedRaftLogWorker.run(SegmentedRaftLogWorker.java:301) ~[master-0.1.0-shaded.jar:?]
        ... 1 more
```

BTW, my version is 0.1.0, but I have tried upgrading ratis to 2.4.1 and the same phenomenon occurs.
This problem can be solved after a new normal leader is re-elected.

### How was this patch tested?
UT

### CODE REVIEW

**Comment by waitinfuture** [comment]
ping @AngersZhuuuu could you take a look at this PR?

**Comment by waitinfuture** [comment]
Hi @xunxunmimi5577 , thanks for the PR! Celeborn uses jira for issue tracking, I've created a jira for this https://issues.apache.org/jira/browse/CELEBORN-501

**Review by waitinfuture — APPROVED** [review]
LGTM, thanks!

**Comment by AngersZhuuuu** [comment]
Title should be `[CELEBORN-495] Add a notifyLogFailed method implementation in StateMachine` ?
cc @waitinfuture

**Comment by xunxunmimi5577** [comment]
Thanks @waitinfuture, I've actually created jira CELEBORN-495.

**Comment by AngersZhuuuu** [comment]
@xunxunmimi5577 Pls add more content to PR desc about this fix.

**Review by AngersZhuuuu — APPROVED** [review]
LGTM

**Pull request merged**
